[package]
name = "create3-miner"
version = "0.1.0"
edition = "2024"
default-run = "create3-miner-neon"

[lib]
name = "create3_miner"
path = "src/lib.rs"

[[bin]]
name = "create3-miner"
path = "src/main.rs"

[[bin]]
name = "create3-miner-neon"
path = "src/bin/create3-miner-neon.rs"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
clap = "4.6.1"
hex = "0.4.3"
rand = "0.10.1"
regex = "1.12.4"
sha3 = "0.10"
